### ISSUE TITLE
Tor tracking issue

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/connect#1040]
- [ ] detect .onion origin in web env and set `setting.useOnionLinks` to true
- [ ] BLOCKCHAIN.CONNECT should return { url: 'btc1.trezor.op`, onionUrl?: 'btc1.xxx.onion` }
- [ ] accept proxyAgent options in `setProxy` method
