### ISSUE TITLE
CI / tests tracking issue

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/connect#781]
- [ ] OS runners matrix (osx + windows)
- [ ] collect coverage (jest, karma) from separated CI jobs
- [ ] karma: firefox
- [ ] karma: handle new window opened (popup mode)
- [ ] karma: move jasmine matcher (toMatchObject, expect.any in getFeatures fixtures) move to karma plugin
- [ ] karma: serve from https (webusb case)
- [ ] unit tests for method params
- [ ] unify tests with https://github.com/trezor/trezor-firmware/tree/master/common/tests/fixtures/cardano
